repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        types: [python]
        entry: pylint
        args:
          [
            "-rn",  # Only display messages
            "-sn",  # Don't display the score
            "--rcfile=.pylintrc",  # Use a custom pylint configuration file
            "--load-plugins=pylint.extensions.docparams",  # Correct spelling for extensions
          ]
  - repo: local
    hooks:
    - id: pipenv-update
      name: pipenv-update
      entry: bash -c 'pipenv update && git add Pipfile Pipfile.lock'
      language: system
      pass_filenames: false
      stages: [commit]
    